language: go
go: 
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - tip

notifications:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always

#
# Lines below copied from # https://github.com/versae/neo4j-rest-client/blob/master/.travis.yml
#
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -v -vendor-only
  - sh start-neo4j.sh
  - sh set_neo4j_password.sh

env:
  global:
    - NEO4J_VERSION="3.4.0"
    - NEO4J_URL=http://neo4j:foobar@localhost:7474/db/data/

script:
  - go test -v
